### ISSUE TITLE
Have some questions, hope to get your answer

### ISSUE THREAD

**Issue by ttylx** [jonpharry/isamdocker#4]
Hey, master, thank you for sharing IBM Security Access Manager 9.0.7.0. I saw the installation tutorial you shared on your blog address. Thank you for sharing. I have a question now how to get IBM Security Access Manager 9.0. 5.0. For some reason, I want to use this version of the system is relatively low, can tell me how to get this version, thank you for your enlightenment

**Comment by jonpharry** [comment]
Use the 9.0.5.0 tag to download the Docker images for the 9.0.5.0 version.
I created scripts for 9.0.5.0 version at the time it was current.  I created a Release for these:
    https://github.com/jonpharry/isamdocker/releases/tag/v9.0.5.0-1
My strong recommendation is that you use the latest version.
Also, for how-to questions, I suggest using the community site https://ibm.biz/iamcommunity.
