### ISSUE TITLE
k8s Deployments Not Ready Until Changes Made

### ISSUE THREAD

**Issue by danchirillo** [jonpharry/isamdocker#6]
**Environment**
macOS 10.14.6
minikube version: v1.4.0
kubectl version: 1.16.0

I'm not sure if this is now the expected behavior in k8s v1.16, but when the pods come up, isamdsc, isamruntime and isamwrprp1 (and the corresponding deployments) do not show as Ready until after the steps in Section 5.5.1 are performed:

![isam po](https://user-images.githubusercontent.com/12007310/65822759-8d0bd980-e217-11e9-9a7b-a24649d2dfe9.jpg)

**Suggested Change**
1.  Update the pods and deployments tables on page 14 of SAM906-Kubernetes 20190509.pdf to show the isamdsc,  isamruntime and isamwrprp1 pods and deployments  are Running but not Ready.

2.  If this is indeed the current expected behavior, provide a brief explanation as to why.

**Comment by jonpharry** [comment]
Cookbook not at 9.0.7.0 level and updated to show not ready in screenshots.
