### ISSUE TITLE
Expired Cert on ISAM 9.0.6 Docker Image

### ISSUE THREAD

**Issue by danchirillo** [jonpharry/isamdocker#8]
Not sure if this is the appropriate repo to report this, but I'll give it a shot.

I tried deploying using the cookbooks to deploy ISAM 9.0.6.  Could not get very far due to an expired cert:
![expired cert](https://user-images.githubusercontent.com/12007310/65898906-8f3d7780-e380-11e9-933f-3bca6dce27a5.jpg)

**Comment by jonpharry** [comment]
What were you attempting to do?  What failed?  This expired certificate should not cause any general issues.

**Comment by danchirillo** [comment]
I'll have to go back and do it again to check ;) [Since I'm using your cookbooks, I don't think you'll be shocked I I tell you I'm very new to ISAM ;)]

**Comment by jonpharry** [comment]
Closing since I'm pretty sure this certification expiration is just a warning which can be safely ignored in context of cookbook since not used.
