### ISSUE TITLE
ISAM RP SSL end of file error

### ISSUE THREAD

**Issue by SouthernYoda** [jonpharry/isamdocker#9]
Hi,

I am using the docker-compose command to create the containers and have not made any local edits to the docker compose file.

I am able to connect to the https://isam.iamlab.ibm.com without issues.

I'm trying to connect to the reverse proxy server using https://www.iamlab.ibm.com/ and get a PR_END_OF_FILE_ERROR on Firefox.

I am new to ISAM, would someone know how to resolve this issue?

**Comment by jonpharry** [comment]
You won't be able to connect to the Reverse Proxy until you have created a configuration and published it).  Have a look at this cookbook: https://ibm.biz/isamdockercookbook.

**Comment by SouthernYoda** [comment]
This is exactly the type of resource I have been looking for. 

@jonpharry thank you , keep up the great work you've done so far.

For someone just getting started learning ISAM do you know of any additional resources or exercises that would help me understand the concepts better?
